### PR TITLE
Updates and upgrades

### PR DESCRIPTION
**Pull request by rblopes**
Hi there.

Firstly, thank you for merging the changes I did to `slush-phaser-project` some
time ago. Though, there were reasons I did not sent you a pull request before,
you did the right choice and I apologize for the trouble. Still, I felt that
these changes were not ready to be pulled yet. That work was rather incomplete,
and several needed changes could not be made that time. But now is the time to
address these issues.

This pull request is a huge update to the tool. Many aspects, like the
generators, were reworked and upgraded, adding some new features, but changing
and removing others.
-   The gulp tasks for both game project and the generator were reorganized and
  improved. I think it's easier now to add or change features to them,
  especially for the generators.
-   The generator CLI was removed, and completely replaced with a proper Slush
  generator. The generator is capable of creating Sprite and State classes as
  before, and is easier to extend now.
-   Support for offline cache in final builds is now available. An
  `offline.appcache` file, containing all assets required by the game is
  created.
-   Installation of Bower packages made easier with `main-bower-files` and
  `bundle.js`. Now, every time a new Bower package is added, a `bundle.js` is
  generated, containing all libraries installed with Bower.
-   A project configuration is now provided, for use of both project tasks and
  the project generator.
-   Traceur Compiler was replaced by 6to5.
  
  6to5 is a rather recent ES6-to-ES5 'transpiler', and is a leaner and
  friendlier option, compared to Traceur. Recently, I felt the need to
  replace Traceur, due to breaking changes they introduced to the Compiler in
  recent versions.
  
  Also, 6to5 doesn't require a bulky runtime (but a polyfill), making for
  lighter builds.
  
  With it, though, comes two caveats. One is the need to revert back to
  `almond` as dependency loader. I've found that, for now, AMD is the only
  reliable way of 'transpiling' scripts. The other is that there is no Bower
  package for 6to5 yet, so the polyfill needs to be copied directly from the
  `6to5` node package, which is installed along the generated project.
  
  6to5 is a fast evolving project, and I believe these issues will be
  resolved shortly.
-   The option to customize the installed physics engines was removed.
  
  I [talked to @photonstorm recently](https://github.com/photonstorm/phaser/issues/1517), asking some explanations on how
  custom builds are made, and did some considerations.
  
  I believe you know, by now, that @photonstorm dropped Ninja physics engine
  from the standard build some time ago. That means only Arcade and P2
  physics engines are available in the standard `phaser.js`.
  
  Now, I think its okay to give the users just a simple set of options,
  rather that offering them the opportunity to 'customize' these right in the
  tool. That may sound cool but, in my opinion, its laborious, and not
  pragmatic. You end up writing too much code (I saw you did!) just to
  support these kind of features. If the user needs some specific setting,
  they know what they'll have to do to achieve that. But these kind of
  workarounds shouldn't be covered or endorsed by the tool.
  
  So, instead of offering each physics engine as an option, just offer an
  list of options like the following, with respective script files given:
  -   Arcade only (recommended, default) → `custom/phaser-arcade-physics.js`
  -   P2 and Arcade Physics (standard)   → `phaser.js`
  -   Ninja with Arcade Physics          → `custom/phaser-ninja-physics.js`
  -   No physics engine enabled          → `custom/phaser-no-physics.js`
  
  Please, note that some Phaser features rely on Arcade Physics engine to the
  enabled—Tilemap physics and Emitter Particles, namely. Also, note that all
  physics engine enabled options include Arcade Physics. That's how it is.

Well, that is all I can remember for now. I think, with these features, `slush-
phaser-project` is way ahead of the 'competitors' now :)

I think there could be more to be done but, hopefully, there'll be more
releases. For now, I humbly ask you to review these some. So, what you think?

### CODE REVIEW

**Comment by tomcask** [comment]
Hi, Do you plan to accept the pull request?

**Comment by rblopes** [comment]
Hi again!

It's gone a month and a half now, I'm afraid several of the changes I did there
are outdated already, and with a new Phaser major release around the corner,
that may require some more attention. For me it's okay if that review may take
some time. Well, if you're interested, I may update my fork with the required
updates. So, what you think?

**Comment by pixelpicosean** [comment]
@rblopes Sorry for late reply, I just found these PR. Seems I unchecked the `Watching` option for this repo :P

**Comment by pixelpicosean** [comment]
@rblopes Just find that you've create another cool project based on this, I'm going to link to your repo instead since I've recently switch to Panda and this may not be used any more.

**Pull request merged**
